//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2023_Final.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2023_Final.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mute {
            get {
                object obj = ResourceManager.GetObject("mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic1 {
            get {
                object obj = ResourceManager.GetObject("pic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic11 {
            get {
                object obj = ResourceManager.GetObject("pic11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker {
            get {
                object obj = ResourceManager.GetObject("speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker_2 {
            get {
                object obj = ResourceManager.GetObject("speaker_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unipi_library {
            get {
                object obj = ResourceManager.GetObject("unipi_library", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unipi_main {
            get {
                object obj = ResourceManager.GetObject("unipi_main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students Act
        ///
        ///Το Students Act αποτελεί μια πλατφόρμα ιδεών, όπου οι φοιτητές θα μπορούν να εκφράσουν την άποψή τους πάνω σε θέματα που πιστεύουν πως μπορούν να αλλάξουν και να βελτιώσουν την ακαδημαϊκή τους πορεία. Οι ιδέες αυτές θα είναι σε θέση να υλοποιηθούν σε συνεργασία με τους φορείς του Πανεπιστημίου και να δώσουν μια καλύτερη εμπειρία στους φοιτητές. Το Students Act πραγματοποιείται στο πλαίσιο του TEDx University of Piraeus που λαμβάνει χώρα για πρώτη φορά στο Πανεπιστήμιο Πειραιώς, με θέμα &quot;Beli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Άλλες_Δραστηριότητες {
            get {
                return ResourceManager.GetString("Άλλες_Δραστηριότητες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H αποστολή του Πανεπιστημίου Πειραιώς, στο πλαίσιο που εξ αρχής του ανέθεσε η
        ///Ελληνική Πολιτεία, είναι να εκπαιδεύει, να παράγει νέα γνώση, να καλλιεργεί το πνεύμα
        ///των νέων, να προάγει τις αξίες της ελευθερίας, της δημοκρατίας και της προσφοράς στις
        ///υποθέσεις της Ελλάδας. Ειδικότερα, η αποστολή του Πανεπιστημίου είναι:
        ///1. να παράγει και να μεταδίδει τη γνώση με την έρευνα και τη διδασκαλία, να
        ///προετοιμάζει τους φοιτητές για την εφαρμογή της σε όλους τους τομείς της
        ///οικονομικής και κοινωνικής ζωής,,
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Αποστολή {
            get {
                return ResourceManager.GetString("Αποστολή", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Αποστολή1 {
            get {
                object obj = ResourceManager.GetObject("Αποστολή1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Αποστολή2 {
            get {
                object obj = ResourceManager.GetObject("Αποστολή2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιστημονική Ένωση Αποφοίτων του Πανεπιστημίου Πειραιώς
        ///
        ///Το σωματείο &quot;Επιστημονική Ένωση Αποφοίτων του Πανεπιστημίου Πειραιώς&quot; (Uni.Pi. Alumni Association) ιδρύθηκε το 2017 με έδρα την πόλη του Πειραιά και κεντρική επιδίωξη τη διατήρηση και ενίσχυση των δεσμών των αποφοίτων μας, αλλά και την προαγωγή των αξιών του -όπως αυτές συμπυκνώνονταν στα ιδρυτικά οράματα για αξιοκρατία, ίσες ευκαιρίες και πολυμερή ανάπτυξη της προσωπικότητας- σε ακαδημαϊκό και κοινωνικό επίπεδο.
        ///Οι άξονες αυτοί αντικατοπτρίζονται  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Απόφοιτοι {
            get {
                return ResourceManager.GetString("Απόφοιτοι", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι χώροι του Πανεπιστημίου καλύπτονται από ελεύθερο ασύρματο δίκτυο wi-fi (ssid: unipi), στο οποίο μπορεί οποιοσδήποτε να συνδεθεί για να χρησιμοποιήσει υπηρεσίες πλοήγησης στο διαδίκτυο.
        ///
        ///Για τους εξουσιοδοτημένους χρήστες, είναι επιπλέον δυνατή η πρόσβαση στο διεθνές ακαδημαϊκό δίκτυο Eduroam (www.eduroam.gr), μέσω του οποίου χρήστες από την παγκόσμια ακαδημαϊκή κοινότητα έχουν τη δυνατότητα να χρησιμοποιήσουν απομακρυσμένα και με ασφάλεια τις υπηρεσίες που παρέχει το ακαδημαϊκό τους ίδρυμα. Στη σελίδα  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ασύρματες_Συνδέσεις {
            get {
                return ResourceManager.GetString("Ασύρματες_Συνδέσεις", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ασύρματες_Συνδέσεις1 {
            get {
                object obj = ResourceManager.GetObject("Ασύρματες_Συνδέσεις1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Βιβλιοθήκη του Πανεπιστημίου Πειραιώς απευθύνεται στους καθηγητές, ερευνητές και φοιτητές και αποστολή της είναι η υποστήριξη της εκπαίδευσης και της έρευνας.
        ///
        ///Το ωράριο λειτουργίας της βιβλιοθήκης έχει επεκταθεί για να εξυπηρετεί τις ανάγκες των μελών του Πανεπιστημίου, από τις 8.00 το πρωί έως τις 20.00 το βράδυ, καθημερινά, όλες τις εργάσιμες ημέρες.
        ///
        ///Στο αναγνωστήριο είναι δυνατή η πρόσβαση και των ΑΜΕΑ.
        ///
        ///Website: www.lib.unipi.gr
        ///
        /// 
        ///
        ///Έντυπες και Ο/Α Συλλογές
        ///
        ///Η συλλογή απαρτίζεται από 47. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Βιβλιοθήκη {
            get {
                return ResourceManager.GetString("Βιβλιοθήκη", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Γραφείο Διασύνδεσης του Πανεπιστημίου Πειραιώς ιδρύθηκε το 1997 με χρηματοδότηση από το πρόγραμμα Ε.Π.Ε.Α.Ε.Κ στο πλαίσιο του Β&apos; ΚΠΣ και συνεχίζει να λειτουργεί στο πλαίσιο του ΕΣΠΑ με Επιστημονικό Υπεύθυνο τον Καθηγητή Νικόλαο Γεωργόπουλο.
        ///
        ///Βασική του επιδίωξη είναι η πολύπλευρη υποστήριξη των φοιτητών/αποφοίτων για την ομαλή ένταξή τους στην αγορά εργασίας και για μια επιτυχημένη σταδιοδρομία.
        ///
        ///Προωθεί την ανάπτυξη δυναμικών συνεργασιών και την εξυπηρέτηση τεσσάρων πόλων, των Φοιτητών &amp; Αποφοίτων τ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Γραφείο_Διασύνδεσης {
            get {
                return ResourceManager.GetString("Γραφείο_Διασύνδεσης", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Γραφείο_Διασύνδεσης1 {
            get {
                object obj = ResourceManager.GetObject("Γραφείο_Διασύνδεσης1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στο πλαίσιο της ηλεκτρονικής εξ αποστάσεως εκπαίδευσης και την εφαρμογή της όπως προβλέπεται στην εγκύκλιο του Υφυπουργού Παιδείας, Αρμόδιου για θέματα Ανώτατης Εκπαίδευσης του ΥΠΑΙΘ, το Πανεπιστήμιο Πειραιώς συνεχίζει να υποστηρίζει την ασύγχρονη διδασκαλία, ενώ από τη Δευτέρα 30/3 θα υποστηρίζεται και η σύγχρονη τηλεκπαίδευση. 
        ///
        ///Οι φοιτητές/-τριες παρακαλούνται να ενημερώνονται από τις ιστοσελίδες του Ακαδημαϊκού τους Τμήματος για τις ανακοινώσεις σχετικά με τα ψηφιακά μαθήματα.
        ///
        ///Στο Πανεπιστήμιο Πειρ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Εξ_Αποστάσεως_Εκπαίδευση {
            get {
                return ResourceManager.GetString("Εξ_Αποστάσεως_Εκπαίδευση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κτίρια οδ. Δεληγιώργη &amp; Tσαμαδού: Στο κτίριο της οδού Δεληγιώργη 107 στεγάζονται εργαστήρια και γραφεία καθηγητών του Τμήματος Βιομηχανικής Διοίκησης και Τεχνολογίας,
        ///ενώ στην οδό Τσαμαδού 78 βρίσκονται δύο κτίρια, από τα οποία στο ένα υπάρχουν αίθουσες διδασκαλίας, ενώ στο άλλο στεγάζεται το φοιτητικό εστιατόριο.
        ///
        ///Κτίριο οδ. Γρ. Λαμπράκη 21 &amp; Διστόμου (Εικόνα 1): Στο κτίριο στεγάζονται τα γραφεία καθηγητών του Τμήματος Ναυτιλιακών Σπουδών, καθώς και αίθουσες διδασκαλίας.                              
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Εξωτερικές_Αίθουσες {
            get {
                return ResourceManager.GetString("Εξωτερικές_Αίθουσες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Εξωτερικές_Αίθουσες1 {
            get {
                object obj = ResourceManager.GetObject("Εξωτερικές_Αίθουσες1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Εξωτερικές_Αίθουσες2 {
            get {
                object obj = ResourceManager.GetObject("Εξωτερικές_Αίθουσες2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΣΤΟΙΧΕΙΑ ΕΠΙΚΟΙΝΩΝΙΑΣ
        ///
        ///Διεύθυνση: Μ. Καραολή &amp; Α. Δημητρίου 80, 18534 Πειραιάς
        ///
        ///Τηλ. Κέντρο: 210 4142000
        ///
        ///Fax: 210 4142328.
        /// </summary>
        internal static string Επικοινωνία {
            get {
                return ResourceManager.GetString("Επικοινωνία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Επικοινωνία1 {
            get {
                object obj = ResourceManager.GetObject("Επικοινωνία1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στη διεύθυνση sis-portal.unipi.gr λειτουργεί διαδικτυακή εφαρμογή που καλύπτει τα σπουδαστικά θέματα. Από την εφαρμογή αυτή οι φοιτητές έχουν τη δυνατότητα: 
        ///
        ///- να ενημερώνονται για τα μαθήματα του προγράμματος σπουδών, τους διδάσκοντες, τα προτεινόμενα συγγράμματα καθώς και τις ανακοινώσεις που εκδίδει η Γραμματεία και οι διδάσκοντες.
        ///- να ενημερώνονται για τη βαθμολογία στα μαθήματα που έχουν εξεταστεί
        ///- να υποβάλουν ηλεκτρονικά τις δηλώσεις μαθημάτων κάθε εξαμήνου
        ///- να λαμβάνουν άμεσα και σε ηλεκτρο [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ηλεκτρονική_Γραμματεία {
            get {
                return ResourceManager.GetString("Ηλεκτρονική_Γραμματεία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ηλεκτρονική_Γραμματεία1 {
            get {
                object obj = ResourceManager.GetObject("Ηλεκτρονική_Γραμματεία1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Πανεπιστήμιο Πειραιώς παρέχει στο προσωπικό του, στους υποψήφιους διδάκτορες και μεταδιδάκτορες, καθώς και στους μεταπτυχιακούς φοιτητές υπηρεσία ηλεκτρονικού ταχυδρομείου (email) της μορφής @unipi.gr.
        ///
        ///Η απόκτηση του ηλ. ταχυδρομείου για τις παραπάνω κατηγορίες, εκτός των μεταπτυχιακών φοιτητών, παρέχεται μετά από αίτηση στο Κέντρο Διαχείρισης Δικτύων (γρ. 321, 3ος όροφ. Κεντρικό Κτίριο).
        ///
        ///Οι μεταπτυχιακοί φοιτητές αποκτούν αυτόματα email με τα στοιχεία του ιδρυματικού τους λογαριασμού (που έχουν απ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ηλεκτρονικό_Ταχυδρομείο {
            get {
                return ResourceManager.GetString("Ηλεκτρονικό_Ταχυδρομείο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Από το Ιατρείο παρέχονται υπηρεσίες πρωτοβάθμιας υγείας. Λειτουργεί καθημερινά στο ισόγειο του κεντρικού κτιρίου, γραφείο 003.
        ///
        ///Το ιατρείο είναι πλήρως εξοπλισμένο με ιατροτεχνολογικό υλικό (καρδιογράφο, απινιδωτή, οξυγόνο, αναπηρική καρέκλα, φαρμακευτικό υλικό για ενδοφλέβια, ενδομυϊκή ή από του στόματος αγωγή).
        ///
        ///Καθημερινά εξυπηρετεί τον πληθυσμό του Πανεπιστημίου Ειδικός Παθολόγος και νοσηλεύτρια, ενώ περιστασιακά το επισκέπτεται και Γυναικολόγος.
        ///
        ///Τηλ.: 210 4142166.
        /// </summary>
        internal static string Ιατρείο {
            get {
                return ResourceManager.GetString("Ιατρείο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ιατρείο1 {
            get {
                object obj = ResourceManager.GetObject("Ιατρείο1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Πανεπιστήμιο Πειραιώς ιδρύθηκε ως «Σχολή Βιομηχανικών Σπουδών» το 1938 από το Σύνδεσμο Βιομηχάνων και Βιοτεχνών, σύμφωνα με το Ν.5197/1931 και τον Α.Ν. 28/1936,
        ///που σε συνεργασία με το Σύνδεσμο Ανωνύμων Εταιριών της Ελλάδας έβαλαν ως βάσεις την οικονομική, νομική και τεχνική παιδεία των στελεχών της βιομηχανίας.
        ///
        ///Το 1945 μετονομάσθηκε σε Ανωτέρα Σχολή Βιομηχανικών Σπουδών και σκοπός της ορίσθηκε η συστηματική, θεωρητική και πρακτική κατάρτιση διοικητικών στελεχών.
        ///
        ///Το 1949, με το Ν.Δ. 1245/49, ολοκλ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ιστορία {
            get {
                return ResourceManager.GetString("Ιστορία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ιστορία1 {
            get {
                object obj = ResourceManager.GetObject("Ιστορία1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ιστορία2 {
            get {
                object obj = ResourceManager.GetObject("Ιστορία2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στο κεντρικό κτίριο του Πανεπιστημίου στεγάζονται υπηρεσίες, γραφεία καθηγητών, αμφιθέατρα, αίθουσες διδασκαλίας, κτλ. 
        ///
        ///Πιο συγκεκριμένα:
        ///
        ///Υπόγειο: Βιβλιοθήκη, αναγνωστήριο
        ///
        ///Ισόγειο: Ιατρείο, διατμηματικά εργαστήρια υπολογιστών, κυλικείο
        ///
        ///1ος όρ.: Γραμματείες των Ακαδ. Τμημάτων εκτός των Τμημάτων Πληροφορικής και Ψηφιακών Συστημάτων
        ///
        ///1ος-2ος-3ος όρ.: Αμφιθέατρα και αίθουσες διδασκαλίας
        ///
        ///3ος όρ.: Γραφεία καθηγητών Τμημάτων Χρηματοοικονομικής και Τραπεζικής Διοικητικής, Βιομηχανικής Διοίκησης και [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Κεντρικό_Κτίριο {
            get {
                return ResourceManager.GetString("Κεντρικό_Κτίριο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Κεντρικό_Κτίριο1 {
            get {
                object obj = ResourceManager.GetObject("Κεντρικό_Κτίριο1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Κεντρικό_Κτίριο2 {
            get {
                object obj = ResourceManager.GetObject("Κεντρικό_Κτίριο2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Θεμιστόκλειο Συγκρότημα» (πρώην Ολυμπιακό Κλειστό Γυμναστήριο Άρσης Βαρών), βρίσκεται στην οδό Κυρά της Ρω 4 στη Νίκαια.
        ///
        ///Στεγάζονται αίθουσες του Τμήματος Ψηφιακών Συστημάτων.
        /// </summary>
        internal static string Κτίριο_Νίκαιας {
            get {
                return ResourceManager.GetString("Κτίριο_Νίκαιας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Κτίριο_Νίκαιας1 {
            get {
                object obj = ResourceManager.GetObject("Κτίριο_Νίκαιας1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Κτίριο_Νίκαιας2 {
            get {
                object obj = ResourceManager.GetObject("Κτίριο_Νίκαιας2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Λοιποί_Χώροι {
            get {
                return ResourceManager.GetString("Λοιποί_Χώροι", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Όραμα του Πανεπιστημίου Πειραιώς είναι:
        ///
        ///να είναι ένα Ίδρυμα διεθνούς κύρους στο σύγχρονο Ακαδημαϊκό Χάρτη και να αναγνωρίζεται για:
        ///
        ///- Την αριστεία στην εκπαίδευση και την έρευνα.
        ///
        ///- Την παραγωγή, διάδοση και εφαρμογή γνώσης αιχμής.
        ///
        ///- τον ηγετικό του ρόλο στη διαμόρφωση αξιών και στην αντιμετώπιση σύγχρονων επιστημονικών, κοινωνικών και οικονομικών προκλήσεων..
        /// </summary>
        internal static string Όραμα {
            get {
                return ResourceManager.GetString("Όραμα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Όραμα1 {
            get {
                object obj = ResourceManager.GetObject("Όραμα1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Οι πολιτιστικές ομάδες του Πανεπιστημίου Πειραιώς προσφέρουν στα μέλη της Πανεπιστημιακής κοινότητας την ευκαιρία να ασχοληθούν με τα ενδιαφέροντα τους και να καλλιεργήσουν το ταλέντο τους. Προάγουν τον εθελοντισμό και την ενεργή συμμετοχή των φοιτητών και καλύπτουν ένα ευρύ φάσμα δράσεων.
        ///
        ///Πιο συγκεκριμένα, το Πανεπιστήμιο Πειραιώς διαθέτει τις παρακάτω πολιτιστικές ομάδες:
        ///
        ///- Θεατρική Ομάδα
        ///- Μουσικά Σύνολα
        ///- Ομάδα Σύγχρονου Χορού
        ///- Λογοτεχνικός Κύκλος.
        /// </summary>
        internal static string Πολιτιστικές_Ομάδες {
            get {
                return ResourceManager.GetString("Πολιτιστικές_Ομάδες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Στρατηγική του Πανεπιστημίου διαμορφώνεται και ισχύει για πέντε έτη.
        ///
        ///Οι Στρατηγικοί Στόχοι του Πανεπιστημίου και οι Στόχοι Ποιότητας που τους υποστηρίζουν
        ///είναι οι ακόλουθοι:
        ///
        ///Σ.Σ.1. Παραγωγή, διάδοση και εφαρμογή γνώσης αιχμής, διεύρυνση των οικονομικών,
        ///κοινωνικών και τεχνολογικών επιστημονικών πεδίων του και συνεχής προσαρμογή
        ///των προγραμμάτων σπουδών στις επιστημονικές εξελίξεις και στις ανάγκες της
        ///κοινωνίας, με προσήλωση στις αρχές της επιστημονικής δεοντολογίας.
        ///
        ///	Σ.Π.1.1. Διάπλαση επιστ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Στρατηγική {
            get {
                return ResourceManager.GetString("Στρατηγική", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Στρατηγική1 {
            get {
                object obj = ResourceManager.GetObject("Στρατηγική1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ΠΑΣΠ
        ///- Πανσπουδαστική
        ///- Δίκτυο Αυτόνομων Ριζοσπαστικών Αριστερών Σχημάτων
        ///- ΔΑΠ-ΝΔΦΚ (Ιστοσελίδα: www.dap-papei.gr)
        ///- Αριστερά Σχήματα (Ιστοσελίδα: www.arister.gr).
        /// </summary>
        internal static string Φοιτητικές_Παρατάξεις {
            get {
                return ResourceManager.GetString("Φοιτητικές_Παρατάξεις", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Τμήμα Φοιτητικής Μέριμνας στεγάζεται στο κεντρικό κτίριο του Πανεπιστημίου Πειραιώς, Καραολή &amp; Δημητρίου 80, 1ος  όροφος, γραφείο 114 Α.
        ///
        ///Οι φοιτητές μπορούν να ενημερωθούν σε θέματα:
        ///
        ///- Σίτισης
        ///- Στέγασης
        ///- Στεγαστικού επιδόματος
        ///- Υγειονομικής κάλυψης
        ///- Ευρωπαϊκής κάρτας ασφάλισης
        /// 
        ///Ώρες εξυπηρέτησης κοινού: Δευτέρα, Τετάρτη και Παρασκευή από 11:00 έως 14:00. 
        ///
        ///Τηλέφωνα: 2104142089, 2104142065, 2104142088. 
        ///
        ///E-mail: foitmer@unipi.gr.
        /// </summary>
        internal static string Φοιτητική_Μέριμνα {
            get {
                return ResourceManager.GetString("Φοιτητική_Μέριμνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σύλλογος Φοιτητών Ο Πλάτων
        ///
        ///Ο Σύλλογος φοιτητών Πανεπιστημίου Πειραιώς  «Ο ΠΛΑΤΩΝ» που ιδρύθηκε το 1978 αποτελεί  το μοναδικό συνδικαλιστικό όργανο των φοιτητών του Πανεπιστημίου μας. Ανήκει στην ΕΦΕΕ και τυπικά διοικείται σύμφωνα με τις διατάξεις του καταστατικού του, που είναι εγκεκριμένο από το Πρωτοδικείο Πειραιώς.  Όργανα του Συλλόγου είναι: η Γενική Συνέλευση, το Διοικητικό Συμβούλιο και η Εξελεγκτική Επιτροπή.
        ///
        ///
        ///Σύλλογος Φοιτητών Ωκεανός
        ///
        ///Ο Ωκεανός είναι μη κερδοσκοπικός σύλλογος, πολιτικά ανε [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Φοιτητικοί_Σύλλογοι {
            get {
                return ResourceManager.GetString("Φοιτητικοί_Σύλλογοι", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αγαπητά μέλη του Πανεπιστημίου Πειραιώς
        ///
        ///Αγαπητές Φίλες , Αγαπητοί Φίλοι
        ///
        ///Το Πανεπιστήμιο Πειραιώς είναι ένα σύγχρονο, καινοτόμο,
        ///διεθνώς αναγνωρισμένο κορυφαίο πανεπιστήμιο,
        ///καθοδηγούμενο από τη δέσμευσή του για αριστεία στην
        ///εκπαίδευση και στην έρευνα. Σε όλη την διάρκεια της
        ///λειτουργίας του το Πανεπιστήμιο Πειραιώς έχει συμβάλει
        ///ουσιαστικά στην καλλιέργεια και εδραίωση των επιστημών που
        ///θεραπεύει, τόσο σε ερευνητικό επίπεδο, όσο και με την
        ///παραγωγή επιστημόνων που στελεχώνουν τον ιδιωτικό και        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Χαιρετισμός {
            get {
                return ResourceManager.GetString("Χαιρετισμός", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Χαιρετισμός1 {
            get {
                object obj = ResourceManager.GetObject("Χαιρετισμός1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Χαιρετισμός2 {
            get {
                object obj = ResourceManager.GetObject("Χαιρετισμός2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
