//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2023_Final.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2023_Final.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mute {
            get {
                object obj = ResourceManager.GetObject("mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic1 {
            get {
                object obj = ResourceManager.GetObject("pic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic11 {
            get {
                object obj = ResourceManager.GetObject("pic11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker {
            get {
                object obj = ResourceManager.GetObject("speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker_2 {
            get {
                object obj = ResourceManager.GetObject("speaker_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Απόφοιτοι.
        /// </summary>
        internal static string Απόφοιτοι {
            get {
                return ResourceManager.GetString("Απόφοιτοι", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ασύρματες Συνδέσεις.
        /// </summary>
        internal static string Ασύρματες_Συνδέσεις {
            get {
                return ResourceManager.GetString("Ασύρματες_Συνδέσεις", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βιβλιοθήκη.
        /// </summary>
        internal static string Βιβλιοθήκη {
            get {
                return ResourceManager.GetString("Βιβλιοθήκη", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Γραφείο Διασύνδεσης.
        /// </summary>
        internal static string Γραφείο_Διασύνδεσης {
            get {
                return ResourceManager.GetString("Γραφείο_Διασύνδεσης", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εξ Αποστάσεως Εκπαίδευση.
        /// </summary>
        internal static string Εξ_Αποστάσεως_Εκπαίδευση {
            get {
                return ResourceManager.GetString("Εξ_Αποστάσεως_Εκπαίδευση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ηλεκτρονικές Υπηρεσίες.
        /// </summary>
        internal static string Ηλεκτρονικές_Υπηρεσίες {
            get {
                return ResourceManager.GetString("Ηλεκτρονικές_Υπηρεσίες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ηλεκτρονική Γραμματεία.
        /// </summary>
        internal static string Ηλεκτρονική_Γραμματεία {
            get {
                return ResourceManager.GetString("Ηλεκτρονική_Γραμματεία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ηλεκτρονικό Ταχυδρομείο.
        /// </summary>
        internal static string Ηλεκτρονικό_Ταχυδρομείο {
            get {
                return ResourceManager.GetString("Ηλεκτρονικό_Ταχυδρομείο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ιατρείο.
        /// </summary>
        internal static string Ιατρείο {
            get {
                return ResourceManager.GetString("Ιατρείο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπηρεσίες.
        /// </summary>
        internal static string Υπηρεσίες {
            get {
                return ResourceManager.GetString("Υπηρεσίες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φοιτητικές Παροχές.
        /// </summary>
        internal static string Φοιτητικές_Παροχές {
            get {
                return ResourceManager.GetString("Φοιτητικές_Παροχές", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φοιτητική Ζωή.
        /// </summary>
        internal static string Φοιτητική_Ζωή {
            get {
                return ResourceManager.GetString("Φοιτητική_Ζωή", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φοιτητική Μέριμνα.
        /// </summary>
        internal static string Φοιτητική_Μέριμνα {
            get {
                return ResourceManager.GetString("Φοιτητική_Μέριμνα", resourceCulture);
            }
        }
    }
}
